spring.application.name=radio-streamer

spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/Punto_Venta_Tienda_Pinturas
spring.datasource.url=jdbc:postgresql://localhost:5432/radio-streamer
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.time-zone=America/Mexico_City
